export const NETWORK_REPORT_DIMENSIONS = [
  'DATE',
  'MONTH',
  'WEEK',
  'AD_UNIT',
  'APP',
  'AD_TYPE',
  'COUNTRY',
  'FORMAT',
  'PLATFORM',
  'MOBILE_OS_VERSION',
  'GMA_SDK_VERSION',
  'APP_VERSION_NAME',
  'SERVING_RESTRICTION',
] as const;

export const NETWORK_REPORT_METRICS = [
  'AD_REQUESTS',
  'CLICKS',
  'ESTIMATED_EARNINGS',
  'IMPRESSIONS',
  'IMPRESSION_CTR',
  'IMPRESSION_RPM',
  'MATCHED_REQUESTS',
  'MATCH_RATE',
  'SHOW_RATE',
] as const;

export const MEDIATION_REPORT_DIMENSIONS = [
  'DATE',
  'MONTH',
  'WEEK',
  'AD_SOURCE',
  'AD_SOURCE_INSTANCE',
  'AD_UNIT',
  'APP',
  'MEDIATION_GROUP',
  'COUNTRY',
  'FORMAT',
  'PLATFORM',
  'MOBILE_OS_VERSION',
  'GMA_SDK_VERSION',
  'APP_VERSION_NAME',
  'SERVING_RESTRICTION',
] as const;

export const MEDIATION_REPORT_METRICS = [
  'AD_REQUESTS',
  'CLICKS',
  'ESTIMATED_EARNINGS',
  'IMPRESSIONS',
  'IMPRESSION_CTR',
  'MATCHED_REQUESTS',
  'MATCH_RATE',
  'OBSERVED_ECPM',
] as const;

export const CAMPAIGN_REPORT_DIMENSIONS = [
  'DATE',
  'CAMPAIGN_ID',
  'CAMPAIGN_NAME',
  'AD_ID',
  'AD_NAME',
  'PLACEMENT_ID',
  'PLACEMENT_NAME',
  'PLACEMENT_PLATFORM',
  'COUNTRY',
  'FORMAT',
] as const;

export const CAMPAIGN_REPORT_METRICS = [
  'IMPRESSIONS',
  'CLICKS',
  'CLICK_THROUGH_RATE',
  'INSTALLS',
  'ESTIMATED_COST',
  'AVERAGE_CPI',
  'INTERACTIONS',
] as const;

export const AD_FORMATS = [
  'APP_OPEN',
  'BANNER',
  'INTERSTITIAL',
  'NATIVE',
  'REWARDED',
  'REWARDED_INTERSTITIAL',
] as const;

export const PLATFORMS = ['ANDROID', 'IOS'] as const;

export const SORT_ORDERS = ['ASCENDING', 'DESCENDING'] as const;

export const DEFAULT_MAX_REPORT_ROWS = 1000;
export const MAX_REPORT_ROWS_LIMIT = 100000;
